export enum ClassNames {
    BTN = 'btn',
    IMG_CONTAINER = 'images-container',
    FULL_CARD_CONTAINER = 'card card_full',
    BRIEF_CARD_CONTAINER = 'card card_brief',
    STORE_CONTAINER = 'store-container',
    CARD_PRICE = 'card__price',
    CARD_DISCOUNT = 'card__discount',
    CARD_DESCRIPTION = 'card__description',
    TRUNK_BTN = 'trunk-btn',
    PRODUCT_CARD_BTNS_CONTAINER = 'card__btns-container',
    TRUNK_BTN_CHECKED = 'trunk-btn_checked',
    PRODUCT_CARD_TITLE = 'card__title',
    PRODUCT_CARD_IMAGE = 'card__image',
    PRODUCT_CARD_INFO = 'card__info',
    PRODUCT_CARD_PREVIEWS_CONTAINER = 'previews-container',
    IMAGE_PREVIEW = 'image__preview',
    IMAGE_PREVIEW_ACTIVE = 'image__preview_active',
    PAGE_HEADER = 'page-header',
    SIDE_PANEL = 'side-panel',
    PRODUCT_CARDS_CONTAINER = 'product-cards',
    SEARCH_INPUT_CONTAINER = 'search-input-container',
    SEARCH_INPUT = 'search-input',
    SEARCH_INPUT_LABEL = 'search-input__label',
}
